version: "3"
services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
  go-surl:
    image: go-surl
    container_name: go-surl
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=""
      - PORT=80
      - GIN_MODE=release
    ports:
      - "80:80"
    depends_on:
      - redis